buildings:
    resources:
        temple:
            wood: 2
            clay: 2
        castle:
            wood: 2
            clay: 2
        windmill:
            wood: 2
            clay: 2
    hierarchies:
        temple:
            castle: 1
            windmill: 1
