buildings:
    temple:
        resources:
            wood: 2
            clay: 2
    castle:
        resources:
            wood: 2
            clay: 2
    windmill:
        resources:
            wood: 2
            clay: 2
